language: cpp

#jobs:
#  include:
#  - os: osx

#    compiler:
#    - gcc
#    - clang
	
#    before_install:
#    - brew update
#    - brew install ruby-build
#    - brew install rbenv
#    - rbenv install 2.6.3
#    - rbenv global 2.6.3
#    - brew install qt5
#    - brew link qt5 --force
    
#    script:
#    - qmake -spec macx-xcode bulkClub.pro
#    - xcodebuild -list -project bulkClub.xcodeproj
#    - xcodebuild -scheme bulkClub build
	
os: linux
compiler:
- gcc
- clang

dist: bionic
#    - xenial
#    - bionic

  

before_install:
- sudo apt-get update
- sudo apt-get install -y devscripts build-essential lintian dh-make
- sudo apt-get install -y libfontconfig1 mesa-common-dev 
- sudo apt-get install -y libgul-mesa-dev 
- sudo apt-get install -y qtdeclarative5-dev qt5-default libjack-jack2-dev
- sudo apt-get install -y sqlite3

script:
- qmake bulkClub.pro
- make 


